### ISSUE TITLE
:/

### ISSUE THREAD

**Issue by walmartfaide** [ElectroGamesYT/BO2-Worlds-Smallest-Map#1]
it keeps crashing when i  try to open the map

**Comment by ElectroGamesDev** [comment]
Are you not receiving any errors?

**Comment by walmartfaide** [comment]
no. the entire game just crashes

**Comment by ElectroGamesDev** [comment]
That's strange. Just to confirm, you were trying to play the map Town? Also do you have any other scripts installed?

**Comment by walmartfaide** [comment]
Yes. Town from tranzit. But  not on tranzit. Survival on town. No I have no other scripts installed

**Comment by ElectroGamesDev** [comment]
This is an issue with the recent version of Plutonium.
There is nothing I can do, we will just need to wait until Plutonium fixes the issue.
Thanks for the report.
